version: "3"
services:
  gift-voucher-mysql:
    container_name: gift-voucher-mysql
    image: mysql:8.0.26
    platform: linux/amd64 # M1/M2 칩 호환성 보장
    environment:
      MYSQL_DATABASE: gift-voucher-mysql
      MYSQL_ROOT_PASSWORD: ${DOCKER_PW}
    ports:
      - "13306:3306"
    volumes:
      - mysql_data:/var/lib/mysql # 데이터 영속성을 위해 볼륨 추가

volumes:
  mysql_data:
